prjWEBMVC/Models/RecipeService.cs
using projectBusiness;
using projectModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace prjWEBMVC.Models
{
    public class RecipeService
    {
        BLLRecipe bll = new BLLRecipe();

        public List<Recipe> GetRecipes() {
            return bll.GetDanhSachRecipe();
        }

        public List<Recipe> GetRecipeWithId(int id) {
            return bll.GetRecipesWithWriterId(id);
        }

        public bool AddOneRecipe(Recipe recipe) {
            return bll.AddRecipe(recipe);
        }

        public bool DeleteOneRecipe(int id) {
            return bll.DeleteRecipe(id);
        }

        public bool UpdateOneRecipe(Recipe recipe) {
            return bll.UpdateRecipe(recipe);
        }

        public Recipe GetOneRecipe(int id) {
            return bll.GetRecipe(id);
        }

    }
}

prjWEBMVC/Models/Writers.cs
using projectBusiness;
using projectModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace prjWEBMVC.Models
{
    public class Writers
    {
        BLLWiter bll = new BLLWiter();

        public List<Write> GetList() {
           return bll.GetList();
        }

        public Write AddWrite(Write write) {
            return bll.AddWrite(write);
        }

        public Write RemoveWrite(Write write) {
            return bll.RomoveWrite(write);
        }

        public Write GetWrite(int id) {
            return bll.GetWrite(id);
        }

        public Write Update(Write write) {
            return bll.UpdateWrite(write);
        }
    }
}

prjWEBMVC/Controllers/HomeController.cs
using prjWEBMVC.Models;
using projectModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace prjWEBMVC.Controllers
{
    public class HomeController : Controller
    {

        Writers w = new Writers();

        public ActionResult Index()
        {
            var list = w.GetList();
            return View(list);
        }

        public ActionResult Create()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
        [HttpPost]
        public ActionResult Create(Write write)
        {
            ViewBag.Message = "Your application description page.";
            if (ModelState.IsValid) {

                if (write != null)
                {
                    w.AddWrite(write);
                    return RedirectToAction("Index");
                }
                else {
                    ModelState.AddModelError("", "Write Not Null!");
                }
            }
             ModelState.AddModelError("","Error validation!");
            return View(write);
        }


        public ActionResult Edit(int id)
        {
            var write = w.GetWrite(id);
            ViewBag.Message = "Your contact page.";
            if (write !=null) {
                return View(write);
            }
            ModelState.AddModelError(null,"Not Object!");
            return View();
        }
        [HttpPost]
        public ActionResult Edit(Write write)
        {
            if (write!=null) {
                w.Update(write);
                return RedirectToAction("Index");
            }
            ViewBag.Message = "Your contact page.";
            ModelState.AddModelError(null, "Not Object For Edit!");
            return View();
        }

        public ActionResult Delete(int id) {
            var write = w.GetWrite(id);
            return View(write);
        }
        [HttpPost]
        public ActionResult Delete(Write write)
        {
            var write1 = w.GetWrite(write.Id);
            if (write1 != null) {
                w.RemoveWrite(write1);
                return RedirectToAction("Index");
            }
            ModelState.AddModelError(null, "Not Delete!");
            return View(write1);
        }

        public ActionResult Details(int id) {
            return View(w.GetWrite(id));
        }
    }
}

prjWEBMVC/Controllers/RecipeController.cs
using prjWEBMVC.Models;
using projectModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace prjWEBMVC.Controllers
{
    public class RecipeController : Controller
    {
        Writers w = new Writers();
        RecipeService recipe = new RecipeService();
        // GET: Recipe
        public ActionResult Index()
        {
            return View(recipe.GetRecipes());
        }

        public PartialViewResult DisplayPartialView()
        {
            return PartialView(w.GetList()); 
        }

        public ActionResult GetRecipeWithWriter(int id) {
            return View(recipe.GetRecipeWithId(id));
        }

        public ActionResult Insert() {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Insert(Recipe recipeobj)
        {
            if (ModelState.IsValid && recipe.AddOneRecipe(recipeobj)) {
                return RedirectToAction("Index");
            }
            return View(recipeobj);
        }

        public ActionResult Edit(int id) {
            return View(recipe.GetOneRecipe(id));

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Recipe recipeobj)
        {
            if (ModelState.IsValid && recipe.UpdateOneRecipe(recipeobj))
            {
                return RedirectToAction("Index");
            }
            return View();

        }

        public ActionResult Delete(int id) {
            return View(recipe.GetOneRecipe(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Recipe recipeobj) {
            if (recipe.DeleteOneRecipe(recipeobj.Id))
            {
                return RedirectToAction("Index");
            }
            return View();
        }


        public ActionResult Detail(int id) {
            return View(recipe.GetOneRecipe(id));
        }

    }
}

prjWEBMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

prjWEBMVC/Views/Home/Add.cshtml
@model projectModel.Write

@{
    ViewBag.Title = "Add";
}

<h2>Add</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Write</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

prjWEBMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

prjWEBMVC/Views/Home/Create.cshtml
@model projectModel.Write

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Write</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

prjWEBMVC/Views/Home/Delete.cshtml
@model projectModel.Write

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Write</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

prjWEBMVC/Views/Home/Details.cshtml
@model projectModel.Write

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Write</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

prjWEBMVC/Views/Home/Edit.cshtml
@model projectModel.Write

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Write</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

prjWEBMVC/Views/Home/Index.cshtml
@model IEnumerable<projectModel.Write>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

prjWEBMVC/Views/Recipe/Delete.cshtml
@model projectModel.Recipe

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Recipe</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model=>model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WriteId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WriteId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

prjWEBMVC/Views/Recipe/Detail.cshtml
@model projectModel.Recipe

@{
    ViewBag.Title = "Detail";
}

<h2>Detail</h2>

<div>
    <h4>Recipe</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WriteId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WriteId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

prjWEBMVC/Views/Recipe/DisplayPartialView.cshtml
@model IEnumerable<projectModel.Write>

@{
    ViewBag.Title = "DisplayPartialView";
}

<ul>
    @foreach (var item in Model) { 
    <li><a href="@Url.Action("GetRecipeWithWriter","Recipe", new {@id = item.Id})">@item.Name</a></li>
    }
</ul>

prjWEBMVC/Views/Recipe/Edit.cshtml
@model projectModel.Recipe

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Recipe</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WriteId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WriteId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WriteId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

prjWEBMVC/Views/Recipe/GetRecipeWithWriter.cshtml
@model IEnumerable<projectModel.Recipe>

@{
    ViewBag.Title = "GetRecipeWithWriter";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<div style="width:80%; margin-left:30px;">
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Content)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WriteId)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Content)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.WriteId)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>
</div>

prjWEBMVC/Views/Recipe/Index.cshtml
@model IEnumerable<projectModel.Recipe>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<div style="width:80%; margin-left:30px;">
    <p>
        @Html.ActionLink("Create New", "Insert")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Content)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WriteId)
            </th>
            <th>Action</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Content)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.WriteId)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Detail", "Detail", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>
</div>

prjWEBMVC/Views/Recipe/Insert.cshtml
@model projectModel.Recipe

@{
    ViewBag.Title = "Insert";
}

<h2>Insert</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Recipe</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WriteId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WriteId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WriteId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

prjWEBMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Recipe", "Index", "Recipe")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

prjWEBMVC/Views/Shared/_LayoutPage.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/css/recipe.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="total">
        <div class="header">
            <h2 style="color:red;">LOGO</h2>
        </div>
        <div class="nav">
            <a>Home | </a>
            <a>Đăng Ký | </a>
            <a>Đăng Nhập</a>

        </div>
        <div class="left">
            <div style="margin:3px;">
                <h3 style="text-align:center;">Writers</h3>
                @Html.Action("DisplayPartialView", "Recipe");
            </div>
        </div>
        <div class="right">
            <div style="margin:5px;">
                @RenderBody()
            </div>
        </div>
        <div class="footer">
            <h4>FIT-IUH</h4>
            <h4>LE VAN TAI - 18093421</h4>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>